import { ArrowLeft, CheckCircle2, Clock3, FileText, Lightbulb, ListChecks, Sparkles, Video } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { ParticipantAvatars } from '../components/ParticipantAvatars'
import { formatDuration, formatMeetingDate } from '../components/MeetingCard'
import { getMeetingById } from '../data/meetings'

export function MeetingDetailPage() {
  const { meetingId } = useParams()
  const meeting = getMeetingById(meetingId)

  if (!meeting) {
    return (
      <div className="page not-found-page">
        <span className="meeting-recording-icon"><Video size={19} /></span>
        <h1>Call not found</h1>
        <p>This meeting may have been removed or the link may be incorrect.</p>
        <Link className="primary-button" to="/calls"><ArrowLeft size={16} />Back to My Calls</Link>
      </div>
    )
  }

  return (
    <div className="page detail-page">
      <Link className="back-link" to="/calls"><ArrowLeft size={16} />All calls</Link>
      <div className="detail-heading">
        <div className="detail-heading-copy">
          <span className="detail-type"><Video size={14} />{meeting.type}</span>
          <h1>{meeting.title}</h1>
          <div className="detail-meta">
            <span>{formatMeetingDate(meeting.date)}</span>
            <span className="subline-dot">·</span>
            <span><Clock3 size={14} />{formatDuration(meeting.durationMinutes)}</span>
          </div>
        </div>
        <div className="detail-attendees">
          <ParticipantAvatars participants={meeting.participants} limit={5} />
          <span>{meeting.participants.length} participants</span>
        </div>
      </div>

      <section className="summary-panel">
        <div className="section-heading">
          <span className="section-icon summary-icon"><Sparkles size={17} /></span>
          <h2>AI summary</h2>
          <span className="generated-label">Generated by Fathom</span>
        </div>
        <p className="summary-text">{meeting.summary}</p>
        <div className="detail-summary-columns">
          <div>
            <div className="subsection-heading"><ListChecks size={16} /><h3>Action items</h3></div>
            {meeting.actionItems.length > 0 ? (
              <ul className="action-list">
                {meeting.actionItems.map((item) => (
                  <li key={item.text}>
                    <span className="action-check"><CheckCircle2 size={17} /></span>
                    <span className="action-copy">{item.text}<small>{item.owner} <span>·</span> Due {item.due}</small></span>
                  </li>
                ))}
              </ul>
            ) : <p className="muted-note">No action items captured.</p>}
          </div>
          <div>
            <div className="subsection-heading"><Lightbulb size={16} /><h3>Highlights</h3></div>
            <ul className="highlight-list">
              {meeting.highlights.map((highlight) => (
                <li key={highlight.time}>
                  <span className="timestamp-pill">{highlight.time}</span>
                  <span>{highlight.text}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="transcript-panel">
        <div className="section-heading">
          <span className="section-icon transcript-icon"><FileText size={17} /></span>
          <h2>Transcript</h2>
          <span className="transcript-caption">Key moments from this conversation</span>
        </div>
        <div className="transcript-list">
          {meeting.transcriptSnippet.map((entry) => (
            <article className="transcript-entry" key={`${entry.time}-${entry.speaker}`}>
              <time>{entry.time}</time>
              <div><strong>{entry.speaker}</strong><p>{entry.text}</p></div>
            </article>
          ))}
        </div>
      </section>
    </div>
  )
}
