import { ChevronDown, Sparkles } from 'lucide-react'
import { ActionItemsPanel } from './ActionItemsPanel'
import { formatClock } from '../utils/meetingState'

const templateOptions = [
  { id: 'general', label: 'General' },
  { id: 'projectUpdate', label: 'Project Update' },
  { id: 'sales', label: 'Sales' },
  { id: 'oneOnOne', label: '1:1' },
]

export function MeetingSummaryWorkspace({
  meeting,
  selectedTemplate,
  onTemplateChange,
  completed,
  onToggleAction,
  onSeek,
  highlights,
}) {
  const summary = meeting.summaryTemplates[selectedTemplate]

  return (
    <div className="summary-workspace">
      <section className="summary-document">
        <header className="summary-document-header">
          <div className="summary-document-title">
            <span className="summary-ai-icon"><Sparkles size={17} /></span>
            <div><h2>Meeting summary</h2><p>AI notes · generated from this conversation</p></div>
          </div>
          <label className="template-picker">
            <span className="visually-hidden">Summary template</span>
            <select value={selectedTemplate} onChange={(event) => onTemplateChange(event.target.value)}>
              {templateOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}
            </select>
            <ChevronDown size={14} />
          </label>
        </header>

        <div className="summary-sections">
          {summary.sections.map((section, index) => (
            <section className={`summary-section${index === 0 ? ' summary-overview' : ''}`} key={section.title}>
              <div className="summary-section-heading">
                <span className="summary-section-number">{String(index + 1).padStart(2, '0')}</span>
                <h3>{section.title}</h3>
              </div>
              {section.body && <p className="summary-section-body">{section.body}</p>}
              {section.bullets && (
                <ul className="summary-bullets">
                  {section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}
                </ul>
              )}
            </section>
          ))}
        </div>
        <div className="summary-document-footer"><Sparkles size={13} />Generated by Fathom AI <span>·</span> Review before sharing</div>
      </section>

      <aside className="summary-side-column">
        <ActionItemsPanel items={meeting.actionItems} completed={completed} onToggle={onToggleAction} />
        <section className="summary-moments-panel">
          <div className="panel-section-heading">
            <div className="panel-heading-title"><span className="panel-icon moments-panel-icon"><Sparkles size={15} /></span><h2>Key moments</h2></div>
            <span className="action-count">{highlights.length}</span>
          </div>
          <div className="summary-moments-list">
            {highlights.slice(0, 3).map((highlight) => (
              <button className="summary-moment" key={highlight.id} type="button" onClick={() => onSeek(highlight.timestamp)}>
                <span className="summary-moment-time">{formatClock(highlight.timestamp)}</span>
                <span><strong>{highlight.title}</strong><small>{highlight.type}</small></span>
              </button>
            ))}
            {!highlights.length && <p className="empty-moments">Highlights you save will appear here.</p>}
          </div>
        </section>
      </aside>
    </div>
  )
}
