import { useMemo } from 'react'
import { Check, Clock3, Plus, Search } from 'lucide-react'
import { initials } from './ParticipantAvatars'
import { formatClock } from '../utils/meetingState'

function HighlightedText({ text, query }) {
  if (!query) return text
  const escapedQuery = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const parts = text.split(new RegExp(`(${escapedQuery})`, 'ig'))
  return parts.map((part, index) => (
    part.toLowerCase() === query.toLowerCase()
      ? <mark key={`${part}-${index}`}>{part}</mark>
      : part
  ))
}

export function TranscriptWorkspace({
  transcript,
  currentTime,
  activeSegmentId,
  search,
  containerRef,
  onSearchChange,
  onSeek,
  onAddHighlight,
}) {
  const matchingSegments = useMemo(() => {
    const query = search.trim().toLowerCase()
    if (!query) return transcript
    return transcript.filter((segment) =>
      `${segment.speaker} ${segment.text}`.toLowerCase().includes(query),
    )
  }, [search, transcript])

  return (
    <section className="transcript-workspace" aria-label="Meeting transcript">
      <header className="transcript-workspace-header">
        <div>
          <h2>Transcript</h2>
          <p>Jump to any moment in the conversation.</p>
        </div>
        <label className="transcript-search">
          <Search size={15} />
          <span className="visually-hidden">Search transcript</span>
          <input
            type="search"
            placeholder="Search transcript..."
            value={search}
            onChange={(event) => onSearchChange(event.target.value)}
          />
          {search && <span className="transcript-search-count">{matchingSegments.length} results</span>}
        </label>
      </header>

      <div className="transcript-result-meta">
        <span>{search ? `${matchingSegments.length} matching segments` : `${transcript.length} transcript segments`}</span>
        <span><span className="transcript-live-dot" />{formatClock(currentTime)} in recording</span>
      </div>

      <div className="transcript-segments" ref={containerRef}>
        {matchingSegments.length ? matchingSegments.map((segment) => (
          <article
            id={`transcript-${segment.id}`}
            className={`transcript-segment${segment.id === activeSegmentId ? ' is-active' : ''}`}
            key={segment.id}
            data-segment-id={segment.id}
          >
            <button
              className="segment-time"
              type="button"
              onClick={() => onSeek(segment.timestamp)}
              aria-label={`Jump playback to ${segment.time}`}
            >
              <Clock3 size={12} />{segment.time}
            </button>
            <span className="segment-avatar">{initials(segment.speaker)}</span>
            <button
              className="segment-content"
              type="button"
              onClick={() => onSeek(segment.timestamp)}
              aria-label={`Jump to ${segment.speaker} at ${segment.time}`}
            >
              <div className="segment-speaker-row">
                <strong>{segment.speaker}</strong>
                {segment.id === activeSegmentId && <span className="segment-playing"><span />Playing</span>}
              </div>
              <p><HighlightedText text={segment.text} query={search.trim()} /></p>
            </button>
            <button
              className="segment-add-highlight"
              type="button"
              onClick={() => onAddHighlight(segment)}
              aria-label={`Add highlight at ${segment.time}`}
            >
              <Plus size={14} /><span>Add highlight</span>
            </button>
          </article>
        )) : (
          <div className="transcript-empty">
            <span><Search size={18} /></span>
            <strong>No transcript matches</strong>
            <p>Try another name or keyword to search this conversation.</p>
          </div>
        )}
      </div>
      <div className="transcript-footer"><Check size={13} />Transcript generated by Fathom AI</div>
    </section>
  )
}
